CREATE TABLE USER
(
    ID       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME     VARCHAR(255)
);
CREATE TABLE LISTA_USERS
(
    ID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(255),
    ID_USER INT UNSIGNED,
    CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USER (ID)
);
